version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone